language: node_js
node_js:
  - '10'
stages:
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: publish
      name: npm publish
      script: 
        - lerna bootstrap
        - lerna run ci-build --stream
        - git checkout master
        - git remote set-url origin https://${GITUB_TOKEN}@github.com/danhuang1202/DrHooks
        - lerna publish --yes