language: node_js
node_js:
  - '10'
stages:
  - name: publish
    if: branch = master
jobs:
  include:
    - stage: publish
      name: npm publish
      script: 
        - lerna bootstrap
        - lerna run ci-build --stream
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - lerna publish from-git --yes